---
- name: Update apk cache
  community.general.apk:
    update_cache: true
  changed_when: false
  tags:
    - package_manager
    - install

- name: Update all apk packages
  community.general.apk:
    upgrade: true
    available: "{{ pm_apk_upgrade_available }}"
  when: pm_update_system
  notify: Reboot
  tags:
    - package_manager
    - install

- name: Install apk packages
  community.general.apk:
    name: "{{ pm_install_packages }}"
    state: present
  when: pm_install_packages | length > 0
  tags:
    - package_manager
    - install

- name: Delete apk packages
  community.general.apk:
    name: "{{ pm_remove_packages }}"
    state: absent
  when: pm_remove_packages | length > 0
  tags:
    - package_manager
    - install
