---
- name: Check boolean package manager values
  ansible.builtin.assert:
    quiet: true
    that:
      - lookup('vars', item) | type_debug == 'bool'
    msg: "Invalid value for {{ item }}. Use a boolean value."
  loop:
    - pm_apk_upgrade_available
    - pm_update_system
    - pm_security_only
    - pm_gpgcheck
    - pm_disable_rhnsd
    - pm_autoremove
    - pm_purge
    - pm_reboot_after_update
  tags:
    - package_manager
    - validate

- name: Check integer variables
  ansible.builtin.assert:
    quiet: true
    that:
      - pm_cache_valid_time | int(-1) >= 0
    msg: Invalid integer value for pm_cache_valid_time
  tags:
    - package_manager
    - validate

- name: Check if APT upgrade command is valid
  ansible.builtin.assert:
    quiet: true
    that:
      - pm_apt_upgrade_command in ['dist', 'full', 'safe', 'yes']
    msg: "Invalid value for pm_apt_upgrade_command. Valid values are 'dist', 'full', 'safe', and 'yes'."
  tags:
    - package_manager
    - validate
