---
# tasks file for package_manager

- name: Check package system variables
  ansible.builtin.include_tasks: asserts.yml
  tags:
    - package_manager
    - validate

- name: Perform package system tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['pkg_mgr'] }}_packages.yml"
  tags:
    - package_manager
    - install
