---
- name: Update pacman cache
  community.general.pacman:
    update_cache: true
  changed_when: false
  tags:
    - package_manager
    - install

- name: Update all pacman packages
  community.general.pacman:
    upgrade: true
  when: pm_update_system
  notify: Reboot
  tags:
    - package_manager
    - install

- name: Install pacman packages
  community.general.pacman:
    name: "{{ pm_install_packages }}"
    state: present
  when: pm_install_packages | length > 0
  tags:
    - package_manager
    - install

- name: Delete pacman packages
  community.general.pacman:
    name: "{{ pm_remove_packages }}"
    state: absent
    extra_args: "{{ '--recursive' if pm_autoremove else '' }}"
  when: pm_remove_packages | length > 0
  tags:
    - package_manager
    - install
