---
- name: Disable rhnsd
  ansible.builtin.service:
    name: rhnsd
    enabled: false
    state: stopped
  failed_when: false
  when:
    - pm_disable_rhnsd
    - ansible_facts['distribution'] != 'Fedora'
  tags:
    - package_manager
    - service

- name: Ensure GPG check is enabled
  when: pm_gpgcheck
  tags:
    - package_manager
    - config
  block:
    - name: Set gpgcheck to 1 in package manager config
      ansible.builtin.replace:
        path: "{{ pkgmgr_redhat_conf }}"
        regexp: '^\s*gpgcheck\s*=\s*([^1]|[1]{2,})\s*$'
        replace: gpgcheck = 1
      tags:
        - package_manager
        - config

    - name: Find all repo files in /etc/yum.repos.d
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: pkgmgr_yumrepos
      tags:
        - package_manager
        - config

    - name: Set all repo gpgchecks to 1
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^\s*gpgcheck\s*=\s*([^1]|[1]{2,})\s*$'
        replace: gpgcheck = 1
      loop: "{{ pkgmgr_yumrepos.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: item.path not in pm_gpgcheck_excludes
      tags:
        - package_manager
        - config
